trying frontend

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -57,10 +57,11 @@ jobs:
       - name: Build Frontend
         working-directory: ./frontend
         run: npm run build
+            if [ ! -d "dist" ]; then echo "Build folder not found!"; exit 1; fi
 
       # Step 9: Deploy Frontend to S3 and CloudFront
       # aws s3 sync ./frontend/build s3://YOUR_FRONTEND_BUCKET_NAME --delete
       - name: Deploy Frontend
         run: |
-          aws s3 sync ./frontend/build s3://myfrontendbucket3 --delete
+          aws s3 sync ./frontend/dist s3://myfrontendbucket3 --delete
           aws cloudfront create-invalidation --distribution-id E27NHW8AC9BSDB --paths "/*"
